vsphere_server = "vcenter IP/DNS"
vsphere_user = "vcenter username"
vsphere_password = "vcenter password"

vsphere_datacenter = "Datacenter1"
#vsphere_resource_pool = "RP1"
#vsphere_datastore = "datastore1"
#vsphere_network = "network 1"
#vsphere_network1 = "network 2"
#vsphere_network2 = "network 3"
#vsphere_network3 = "network 4"
