vcenter_server = "vcenter ip/dns"
vcenter_username = "vcenter username"
vcenter_cluster = "Cluster-01"
vcenter_datacenter = "Datacenter1"
vcenter_host = "vsphere managed host"
vcenter_datastore = "datastore1"
vcenter_folder = "Templates"
vcenter_password = "vcenter password"
vm_network1 = "Network 1"
vm_network2 = "Network 2"
vm_network3 = "Network 3"
vm_network4 = "Network 4"
os_version = "8"
os_family = "centos"
guest_os_type = "centos7_64Guest"
os_iso_path = "[datastore1] ISO/vyos.iso"
#os_iso_url = "http://mirror.mobap.edu/centos/8.2.2004/isos/x86_64/CentOS-8.2.2004-x86_64-minimal.iso"
iso_checksum = "47AB14778C823ACAE2EE6D365D76A9AED3F95BB8D0ADD23A06536B58BB5293C0"
root_disk_size = 24000
connection_username = "vyos"
connection_password = "vyos"
boot_command = [
  #"<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"
  "vyos<enter><wait>vyos<enter><wait>config<enter><wait>set interfaces ethernet eth0 address dhcp<enter><wait>set service ssh<enter><wait>commit<enter><wait>save<enter><wait>"
]
http_ip = "user workstation ip"
http_directory    = "scripts"